package arytmetykaPackage;


/**
* arytmetykaPackage/DzieleniePrzezZero.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Arytmetyka.idl
* sobota, 6 czerwca 2020 18:12:09 CEST
*/

public final class DzieleniePrzezZero extends org.omg.CORBA.UserException
{

  public DzieleniePrzezZero ()
  {
    super(DzieleniePrzezZeroHelper.id());
  } // ctor


  public DzieleniePrzezZero (String $reason)
  {
    super(DzieleniePrzezZeroHelper.id() + "  " + $reason);
  } // ctor

} // class DzieleniePrzezZero
