
/**
* arytmetyka.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Arytmetyka.idl
* sobota, 6 czerwca 2020 18:12:09 CEST
*/

public interface arytmetyka extends arytmetykaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface arytmetyka
